pipeline:
  auth:
    image: scottlackey/drone-auth-ecr
    commands:
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - aws ecr get-login --region us-east-1 | bash
      - docker pull 404825630592.dkr.ecr.us-east-1.amazonaws.com/blinemedical/meteor-scripts:meteor-scripts-master.1.1.0-dev.14882
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    secrets: [ AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY ]

  deploy_database:
    image: scottlackey/drone-auth-ecr
    commands:
      - docker run 404825630592.dkr.ecr.us-east-1.amazonaws.com/blinemedical/meteor-scripts:meteor-scripts-master.1.1.0-dev.14882 postgres/db.js deploy --host=$POSTGRES_HOST -u="$POSTGRES_USER" -p="$POSTGRES_PASSWORD" -d="$POSTGRES_DATABASE"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets: [ POSTGRES_HOST, POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DATABASE ]
  
  ecs:
    image: peloton/drone-ecs
    region: us-east-1
    cluster: api-feature-cluster
    access_key: $$AWS_ACCESS_KEY_ID
    secret_key: $$AWS_SECRET_ACCESS_KEY
    family: api-MET-3275-has-rows
    docker_image: 404825630592.dkr.ecr.us-east-1.amazonaws.com/blinemedical/meteor-api
    tag: meteor-api-MET-3275-has-rows.1.0.2-dev.13756
    service: api-MET-3275-has-rows
    desired_count: 1
    deployment_configure: 50 200